keys:
  - &serpentian age1akv2vzewt82ufvjq0rccazucpurr95weyz9reg8exgkk6kjld99qcl0vmz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *serpentian
