# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5e0f221b-c24c-4655-b9a7-8fb08ba36fad";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E50-F427";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/becc9d37-d481-469a-9e62-063e6082d67f";
      fsType = "ext4";
    };

  fileSystems."/home/serpentian/Games/ssd" =
    {
        device = "/dev/disk/by-uuid/43702a06-1dd1-4fe0-bf61-20b45a3545a2";
        fsType = "ext4";
        options = [ "defaults" "users" "exec"];
    };

  fileSystems."/home/serpentian/Games/hdd" =
    {
        device = "/dev/disk/by-uuid/8b9e0315-ae3f-47b6-a733-edba52aa8925";
        fsType = "ext4";
        options = [ "defaults" "users" "exec"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/58bae934-bc9c-47ba-ab6c-b22ed66ada5e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
