lastfm: ENC[AES256_GCM,data:Qx1UxIUiTQ40TNof,iv:6R0RXIRp+P6wpxaT7z+p5wpMq0N1FqLMh2GZddK2C/Q=,tag:nEI15hsOAB9UGiZLd3pmEg==,type:str]
listenbrainz: ENC[AES256_GCM,data:SD1+xaVy8vppu41Cbd/5LNkGrmGdNQFbAixFtxPraevOpG08,iv:v8an1Z7gV+P01GRkmsTxm/Kt7S9kLMN4FRt7UiMH0A0=,tag:laZmKwFNXH9RMCoPXBvhlA==,type:str]
sops:
    age:
        - recipient: age1akv2vzewt82ufvjq0rccazucpurr95weyz9reg8exgkk6kjld99qcl0vmz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOWNJRlNNbmxxUmZSM3dY
            UVJVMmM1ZlFRanUrWFBwQ3BZVnB3VFRyTWh3CnByT3hmeDh4Z0hWMVByb3dteGJW
            NmVQK05yMWdDMUoyeCtUdzVRaG93dk0KLS0tIENGbkpodFc5dzduNnIwQ1Y2akpV
            T2hLWGh2M2VLdkp2NjBDTHdIMG9BN00KLGtJfQpf3Tec+K4VofmFiXXt72fCxoIo
            iDOX8G5HywqT46jUM8Ob2d5kvsbspfRa9V3yqPB76rjxQvGxiAFDKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T04:28:11Z"
    mac: ENC[AES256_GCM,data:2FfIWWjjeEE6AXdX3CWl5HqqDiXkK35B3twfm3Iq+ErPAfLRr3bpY8Ejz7gafaVgDDqyPO3zD4dMBma/fpnUSBu4n0CNzq/wP4xrL6t9TipyLISV10oPCfVU2ka24RioSv6wF3dPGbr5tA/MRh6J4j0GxzlMGEz/PMGhe0YWnpw=,iv:DFpEWqvdpCOLB4TxVQk5hHortRB/53gQ7z2Y4CAYaOQ=,tag:SwODdTwkM2BTHeTOyyF13A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
